/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package placement1;

import com.sun.glass.events.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author Anchit Chawla
 */
public class editcompany extends javax.swing.JFrame {

    /**
     * Creates new form editcompany
     */
    public editcompany() {
        initComponents();
    }
    String j;
    public editcompany(String o) {
        initComponents();
        
        j=o;
        try
        {
            myconnection obj=new myconnection();
            String k="select * from tbcompany where cusername=?";
        PreparedStatement pst=obj.db.prepareStatement(k);
        pst.setString(1,j);
        ResultSet rs;
        rs=pst.executeQuery();
        if(rs.next())
        {
            t1.setText(rs.getString("cname"));
            t4.setText(rs.getString("director"));
            t5.setText(rs.getString("location"));
            t6.setText(rs.getString("profile"));
            t7.setText(rs.getString("contact"));
            t8.setText(rs.getString("email"));
        }
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label4 = new java.awt.Label();
        t5 = new java.awt.TextField();
        label8 = new java.awt.Label();
        t1 = new java.awt.TextField();
        t6 = new java.awt.TextField();
        t4 = new java.awt.TextField();
        t7 = new java.awt.TextField();
        t8 = new java.awt.TextField();
        label7 = new java.awt.Label();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        label1.setText("Company Name");
        jPanel1.add(label1);
        label1.setBounds(230, 110, 94, 20);

        label5.setText("Location");
        jPanel1.add(label5);
        label5.setBounds(230, 200, 51, 20);

        label6.setText("Profile");
        jPanel1.add(label6);
        label6.setBounds(230, 240, 39, 20);

        label4.setText("Director");
        jPanel1.add(label4);
        label4.setBounds(230, 160, 100, 20);
        jPanel1.add(t5);
        t5.setBounds(410, 200, 100, 20);

        label8.setText("Email-Id");
        jPanel1.add(label8);
        label8.setBounds(230, 330, 50, 20);
        jPanel1.add(t1);
        t1.setBounds(410, 110, 100, 20);
        jPanel1.add(t6);
        t6.setBounds(410, 240, 100, 20);
        jPanel1.add(t4);
        t4.setBounds(410, 160, 100, 20);

        t7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t7KeyTyped(evt);
            }
        });
        jPanel1.add(t7);
        t7.setBounds(410, 280, 100, 20);
        jPanel1.add(t8);
        t8.setBounds(410, 330, 100, 20);

        label7.setText("Contact Number");
        jPanel1.add(label7);
        label7.setBounds(230, 280, 94, 20);

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(320, 390, 90, 23);

        jLabel2.setFont(new java.awt.Font("AR BLANCA", 3, 36)); // NOI18N
        jLabel2.setText("Edit Company Details");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(200, 20, 370, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Anchit Chawla\\Desktop\\SeeingSpots_1400x900-1024x658.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 790, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
            myconnection obj=new myconnection();
            String q="update tbcompany set cname=?,director=?,location=?,profile=?,contact=?,email=? where cusername=?";
            PreparedStatement pst=obj.db.prepareStatement(q);
            pst.setString(1,t1.getText());
            pst.setString(2,t4.getText());
            pst.setString(3,t5.getText());
            pst.setString(4,t6.getText());
            pst.setString(5,t7.getText());
            pst.setString(6,t8.getText());
            pst.setString(7,j);
            pst.executeUpdate();
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void t7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t7KeyTyped
 char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACKSPACE)||c==KeyEvent.VK_DELETE)
        {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_t7KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editcompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editcompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editcompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editcompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editcompany().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.TextField t1;
    private java.awt.TextField t4;
    private java.awt.TextField t5;
    private java.awt.TextField t6;
    private java.awt.TextField t7;
    private java.awt.TextField t8;
    // End of variables declaration//GEN-END:variables
}
