 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package placement1;

import java.sql.PreparedStatement;

/**
 *
 * @author Anchit Chawla
 */
public class question extends javax.swing.JFrame {

    /**
     * Creates new form question
     */
    public question() {
        initComponents();
    }
    String jk;
     public question(String m) {
        initComponents();
        jk=m;
       c1.add("1");
       c1.add("2");
       c1.add("3");
       c1.add("4");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label4 = new java.awt.Label();
        jButton1 = new javax.swing.JButton();
        label2 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label1 = new java.awt.Label();
        label7 = new java.awt.Label();
        c1 = new java.awt.Choice();
        t11 = new java.awt.TextField();
        t22 = new java.awt.TextField();
        t3 = new java.awt.TextField();
        t4 = new java.awt.TextField();
        t5 = new java.awt.TextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        label4.setText("Option 3");
        jPanel1.add(label4);
        label4.setBounds(80, 210, 100, 20);

        jButton1.setText("DONE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(260, 390, 80, 23);

        label2.setText("Option 1");
        jPanel1.add(label2);
        label2.setBounds(80, 100, 100, 20);

        label5.setText("Option 4");
        jPanel1.add(label5);
        label5.setBounds(80, 270, 100, 20);

        label6.setText("Correct Answer");
        jPanel1.add(label6);
        label6.setBounds(90, 340, 88, 20);

        label1.setText("Option 2");
        jPanel1.add(label1);
        label1.setBounds(80, 150, 100, 20);

        label7.setText("Question");
        jPanel1.add(label7);
        label7.setBounds(80, 50, 100, 20);
        jPanel1.add(c1);
        c1.setBounds(360, 340, 100, 20);
        jPanel1.add(t11);
        t11.setBounds(360, 50, 190, 40);
        jPanel1.add(t22);
        t22.setBounds(360, 100, 190, 40);
        jPanel1.add(t3);
        t3.setBounds(360, 150, 190, 40);
        jPanel1.add(t4);
        t4.setBounds(360, 210, 190, 40);
        jPanel1.add(t5);
        t5.setBounds(360, 270, 190, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Anchit Chawla\\Desktop\\SeeingSpots_1400x900-1024x658.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 640, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
            myconnection obj=new myconnection();
            String a,b,c,d,e,f;
            a=t11.getText();
            b=t22.getText();
            c=t3.getText();
            d=t4.getText();
            e=t5.getText();
            
            String q="insert into tbquestion(cname,op1,op2,op3,op4,cans,cusername)values(?,?,?,?,?,?,?)";
            PreparedStatement pst=obj.db.prepareStatement(q);
            pst.setString(1,t11.getText());
            pst.setString(2,t22.getText());
            pst.setString(3,t3.getText());
            pst.setString(4,t4.getText());
            pst.setString(5,t5.getText());
            pst.setString(6,c1.getSelectedItem());
            pst.setString(7,jk);
            pst.executeUpdate();
            
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new question().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice c1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.TextField t11;
    private java.awt.TextField t22;
    private java.awt.TextField t3;
    private java.awt.TextField t4;
    private java.awt.TextField t5;
    // End of variables declaration//GEN-END:variables
}
