/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package placement1;

import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author Anchit Chawla
 */
public class update extends javax.swing.JFrame {

    /**
     * Creates new form update
     */
    public update() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        t1 = new java.awt.TextField();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        label13 = new java.awt.Label();
        label16 = new java.awt.Label();
        label8 = new java.awt.Label();
        t15 = new java.awt.TextField();
        jButton1 = new javax.swing.JButton();
        label9 = new java.awt.Label();
        label10 = new java.awt.Label();
        t9 = new java.awt.TextField();
        label12 = new java.awt.Label();
        t14 = new java.awt.TextField();
        t11 = new java.awt.TextField();
        label14 = new java.awt.Label();
        t13 = new java.awt.TextField();
        t2 = new java.awt.TextField();
        t3 = new java.awt.TextField();
        t4 = new java.awt.TextField();
        t5 = new java.awt.TextField();
        t6 = new java.awt.TextField();
        t7 = new java.awt.TextField();
        t8 = new java.awt.TextField();
        t12 = new java.awt.TextField();
        label15 = new java.awt.Label();
        jButton2 = new javax.swing.JButton();
        label1 = new java.awt.Label();
        t10 = new java.awt.TextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        jPanel1.add(t1);
        t1.setBounds(250, 30, 90, 20);

        label2.setText("Fname");
        jPanel1.add(label2);
        label2.setBounds(130, 100, 43, 20);

        label3.setText("Lname");
        jPanel1.add(label3);
        label3.setBounds(130, 170, 43, 20);

        label4.setText("father");
        jPanel1.add(label4);
        label4.setBounds(130, 230, 35, 20);

        label5.setText("age");
        jPanel1.add(label5);
        label5.setBounds(130, 290, 40, 20);

        label6.setText("contact");
        jPanel1.add(label6);
        label6.setBounds(130, 350, 43, 20);

        label7.setText("email");
        jPanel1.add(label7);
        label7.setBounds(130, 410, 35, 20);

        label13.setText("grade");
        jPanel1.add(label13);
        label13.setBounds(430, 340, 36, 20);

        label16.setText("password");
        jPanel1.add(label16);
        label16.setBounds(430, 460, 59, 20);

        label8.setText("address");
        jPanel1.add(label8);
        label8.setBounds(430, 100, 50, 20);

        t15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t15ActionPerformed(evt);
            }
        });
        jPanel1.add(t15);
        t15.setBounds(590, 460, 90, 20);

        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(440, 30, 90, 23);

        label9.setText("stream");
        jPanel1.add(label9);
        label9.setBounds(430, 160, 43, 20);

        label10.setText("tenth");
        jPanel1.add(label10);
        label10.setBounds(430, 230, 31, 20);

        t9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t9ActionPerformed(evt);
            }
        });
        jPanel1.add(t9);
        t9.setBounds(590, 160, 90, 20);

        label12.setText("twelve");
        jPanel1.add(label12);
        label12.setBounds(430, 290, 38, 20);
        jPanel1.add(t14);
        t14.setBounds(250, 460, 90, 20);
        jPanel1.add(t11);
        t11.setBounds(590, 290, 90, 20);

        label14.setText("technical");
        jPanel1.add(label14);
        label14.setBounds(430, 400, 53, 20);
        jPanel1.add(t13);
        t13.setBounds(590, 400, 90, 20);

        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        jPanel1.add(t2);
        t2.setBounds(250, 100, 90, 20);

        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        jPanel1.add(t3);
        t3.setBounds(250, 170, 90, 20);
        jPanel1.add(t4);
        t4.setBounds(250, 230, 90, 20);

        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });
        jPanel1.add(t5);
        t5.setBounds(250, 290, 90, 20);

        t6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6ActionPerformed(evt);
            }
        });
        jPanel1.add(t6);
        t6.setBounds(250, 350, 90, 20);
        jPanel1.add(t7);
        t7.setBounds(250, 410, 90, 20);

        t8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t8ActionPerformed(evt);
            }
        });
        jPanel1.add(t8);
        t8.setBounds(590, 100, 90, 20);
        jPanel1.add(t12);
        t12.setBounds(590, 340, 90, 20);

        label15.setText("photo");
        jPanel1.add(label15);
        label15.setBounds(130, 460, 35, 20);

        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(350, 500, 110, 23);

        label1.setText("Roll No");
        jPanel1.add(label1);
        label1.setBounds(130, 30, 45, 20);
        jPanel1.add(t10);
        t10.setBounds(590, 230, 90, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Anchit Chawla\\Desktop\\sweet-white-blue-swirl-powerpoint-backgrounds.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 750, 530);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void t15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t15ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
            myconnection obj=new myconnection();
            String q="select * from tbstudent where RollNo=?";
            PreparedStatement pst=obj.db.prepareStatement(q);
            pst.setString(1,t1.getText());
            ResultSet rs;
            rs=pst.executeQuery();
            if(rs.next())
            {
                t2.setText(rs.getString("Fname"));
                t3.setText(rs.getString("Lname"));
                t4.setText(rs.getString("father"));
                t5.setText(""+rs.getString("age"));
                t6.setText(rs.getString("contact"));
                t7.setText(rs.getString("email"));
                t8.setText(rs.getString("address"));
                t9.setText(""+rs.getString("stream"));
                t10.setText(""+rs.getString("tenth"));
                t11.setText(""+rs.getString("twelve"));
                t12.setText(""+rs.getString("grade"));
                t13.setText(rs.getString("technical"));
                t14.setText(rs.getString("photo"));
                t15.setText(rs.getString("password"));
            }
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void t9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t9ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t5ActionPerformed

    private void t8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try
        {
        myconnection obj=new myconnection();
        String q="update tbstudent set Fname=?,Lname=?,father=?,age=?,contact=?,email=?,address=?,stream=?,tenth=?,twelve=?,grade=?,technical=?,photo=?,password=? where RollNo=?";
        PreparedStatement pst=obj.db.prepareStatement(q);
        pst.setString(1,t2.getText());
        pst.setString(2,t3.getText());
        pst.setString(3,t4.getText());
        pst.setString(4, ""+t5.getText());
        pst.setString(5, t6.getText());
        pst.setString(6,t7.getText());
        pst.setString(7,t8.getText());
        pst.setString(8,t9.getText());
        pst.setString(9, ""+t10.getText());
        pst.setString(10, ""+t11.getText());
        pst.setString(11, ""+t12.getText());
        pst.setString(12,t13.getText());
        pst.setString(13,t14.getText());
        pst.setString(14,t15.getText());
        pst.setString(15,t1.getText());
        pst.executeUpdate();

        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void t6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.TextField t1;
    private java.awt.TextField t10;
    private java.awt.TextField t11;
    private java.awt.TextField t12;
    private java.awt.TextField t13;
    private java.awt.TextField t14;
    private java.awt.TextField t15;
    private java.awt.TextField t2;
    private java.awt.TextField t3;
    private java.awt.TextField t4;
    private java.awt.TextField t5;
    private java.awt.TextField t6;
    private java.awt.TextField t7;
    private java.awt.TextField t8;
    private java.awt.TextField t9;
    // End of variables declaration//GEN-END:variables
}
